TASM = tasm
TASM_OPT = /m2 /l
TLINK = tlink
TLINK_OPT = /v

all: compile link

compile:
        $(TASM) $(TASM_OPT) dozmon.asm + tools.asm + args.asm + interpre.asm

link:
        $(TLINK) $(TLINK_OPT) dozmon.obj + tools.obj + args.obj + interpre.obj,dozmon.exe,dozmon.map

clean:
        del *.exe 
        del *.obj
        del *.lst
        del *.map

